New Post: Error Code 137
FalixNodes-Software/help-center pull request #30
Opened 2021-06-24 17:17 UTC by AlbertPM9000

Maybe it could be in a folder called Issues, inside Minecraft, where Korbs can also put the Invalid Bungeecord article

2021-06-24 17:35 UTC, itsjuoum commented
I think there's no need to create a whole new article for this error as it can be easily sovlved without a lot of steps. Instead, it should be included in the [troubleshooting article](https://help.falixnodes.net/falix/general/troubleshooting/), but I'll let @KorbsStudio decide.

2021-06-24 17:40 UTC, AlbertPM9000 commented
> I think there's no need to create a whole new article for this error as it can be easily sovlved without a lot of steps. Instead, it should be included in the [troubleshooting article](https://help.falixnodes.net/falix/general/troubleshooting/), but I'll let @KorbsStudio decide.



> I think there's no need to create a whole new article for this error as it can be easily sovlved without a lot of steps. Instead, it should be included in the [troubleshooting article](https://help.falixnodes.net/falix/general/troubleshooting/), but I'll let @KorbsStudio decide.

Oh I didn't see that article. I think you're right

> I think there's no need to create a whole new article for this error as it can be easily sovlved without a lot of steps. Instead, it should be included in the [troubleshooting article](https://help.falixnodes.net/falix/general/troubleshooting/), but I'll let @KorbsStudio decide.

Oh I didn't see that article. I think you're right.

2021-06-25 03:43 UTC, KorbsStudio requested changes
An error does not deserve an entire article to it's self, but should be put into the error section of the Troubleshoot.md file: https://help.falixnodes.net/falix/general/troubleshooting/#errors

Everything must be done in one file as much as possible.

2021-06-25 03:44 UTC, KorbsStudio commented
Also this is not for Minecraft, so it should be moved under General sub category in Falix.

2021-06-25 17:25 UTC, KorbsStudio commented
Please also mention other information about making sure customers are using the proper version of Java for their selected version of Minecraft and also making sure that they have enough resources used for their server like the correct amount of CPU cores and memory as they can have an impact on the server if not setup properly.

or...I can do this myself, but I'm just giving you a chance.

2021-06-25 17:25 UTC, KorbsStudio commented on docs/minecraft/general/error-code-137.md
> +### Optimize server
Please also mention other information about making sure customers are using the proper version of Java for their selected version of Minecraft and also making sure that they have enough resources used for their server like the correct amount of CPU cores and memory as they can have an impact on the server if not setup properly.

or...I can do this myself, but I'm just giving you a chance.

2021-06-25 18:26 UTC, AlbertPM9000 commented on docs/minecraft/general/error-code-137.md
> +### Optimize server
Do you mean in Optimizing article or error 137 one? I'm a little bit confused as it says you mentioned the Optimizing one but reviewed the 137.

2021-06-25 21:00 UTC, KorbsStudio commented on docs/minecraft/general/error-code-137.md
> +### Optimize server
Obviously optimizations, the error needs to go into the Troubleshooting article.

2021-06-25 21:09 UTC, AlbertPM9000 commented on docs/minecraft/general/error-code-137.md
> +### Optimize server
Done. Can you see changes? I'm pretty new in GitHub, so I don't know if I have to enable something or do something.

2021-06-25 21:50 UTC, KorbsStudio commented on docs/minecraft/general/error-code-137.md
> +### Optimize server
I can move the stuff myself and get things to where they're suppose to be. 
So I'll take it from here.

2021-06-25 21:58 UTC, closed without merging

2021-06-25 21:59 UTC, KorbsStudio commented
Merged manually: https://github.com/FalixNodes-Software/help-center/commit/a2ec39c3a90f949c16973c96a66c26056b1b5517