New Post: Bungeecord custom jar
FalixNodes-Software/help-center pull request #32
Opened 2021-06-27 12:21 UTC by Mocab

Tell me if I did everything right

2021-06-27 13:48 UTC, DaddyChimken commented
Can you also add a small section explaining what Bungeecord is?

2021-06-27 13:49 UTC, DaddyChimken commented on docs/minecraft/Custom_jar/Bungeecord.md
> +![images](https://i.imgur.com/dv8Cp4v.png)
Typo? `[images]` --> `[image]`

2021-06-27 13:50 UTC, Mocab commented
> Can you also add a small section explaining what Bungeecord is?

I'll work on it tomorrow

2021-06-27 13:52 UTC, Mocab commented on docs/minecraft/Custom_jar/Bungeecord.md
> +![images](https://i.imgur.com/dv8Cp4v.png)
Yes

2021-06-27 14:16 UTC, itsjuoum requested changes

2021-06-27 14:16 UTC, itsjuoum commented on docs/minecraft/Custom_jar/Bungeecord.md
> +title:  "Bungeecord"
The title should be the title of the article, briefly explaining what it is going to talk about. This article isn't talking about bungeecord itself, but how to set it up using a custom jar.

2021-06-27 14:16 UTC, itsjuoum commented on docs/minecraft/Custom_jar/Bungeecord.md
> +parent: Custom-jar
The parent should be the name of the folder it is **in** the help center, so it shouldn't contain hyphens. Something like this would be what we are going for: ` Custom Jars`.

2021-06-27 14:16 UTC, itsjuoum commented on docs/minecraft/Custom_jar/Bungeecord.md
> +permalink: /Minecraft/Custom-jar/
The permalink should be in lower case, and contain the path to the file. It should look something like this: `/minecraft/custom-jars/setting-up-bungeecord-with-custom-jar`.

2021-06-27 14:16 UTC, itsjuoum commented on docs/minecraft/Custom_jar/Bungeecord.md
> +2. Click on the bungee.jar file, it should download it.
We could also stretch up the article size in height by reducing the amount of steps. Try to make something like "Go to the [bungee cord download page](https://ci.md-5.net/job/BungeeCord/), click on the bungee.jar file, and it should be downloaded." .

2021-06-27 14:16 UTC, itsjuoum commented on docs/minecraft/Custom_jar/Bungeecord.md
> +![images](https://i.imgur.com/dv8Cp4v.png)
Fix typo to `![image]`.

2021-06-27 14:16 UTC, itsjuoum commented on docs/minecraft/Custom_jar/Custom_jar.md
> +title: Custom_jar
The title shouldn't contain any type of "symbols", because this is what is going to appear in the help center. Make this "Custom Jars"

2021-06-27 14:16 UTC, itsjuoum commented on docs/minecraft/Custom_jar/Custom_jar.md
> +## custom-jar
Remove the hyphen, and capitalize the words correctly. Since this is a folder, we're not going to talk about just one custom jar, so make it plural.

2021-06-27 14:16 UTC, itsjuoum commented on docs/minecraft/Custom_jar/Custom_jar.md
> +permalink: /minecraft/custom-jar
Since this is a folder, we're not going to talk about just one custom jar, so make it plural. "custom-jars"

2021-06-27 14:16 UTC, itsjuoum commented on docs/minecraft/Custom_jar/Bungeecord.md
> +### Restart all your servers, then use the bungee cord server IP and port to join the hub/lobby.
Why make these a header? Remove the "#"

2021-06-27 19:39 UTC, KorbsStudio commented
Using custom jar is already included: https://help.falixnodes.net/minecraft/general/getting-started/#using-a-custom-jar

Getting a custom jar for Bungeecord will be mentioned: https://help.falixnodes.net/falix/general/troubleshooting/#corrupted-bungeecord-jar-file

2021-06-27 19:39 UTC, closed without merging

2021-06-28 00:43 UTC, Mocab commented
Problem is I've already wrote 4 long guides on using custom jars, should I throw them out the window?