New post: GeyserMC
FalixNodes-Software/help-center pull request #38
Opened 2021-08-08 12:51 UTC by Mocab

Could someone check if you can use extra ports? I dont have bedrock

2021-08-08 14:24 UTC, itsjuoum requested changes

2021-08-08 14:24 UTC, itsjuoum commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +    <img style="border-radius: 7px;" src="https://raw.githubusercontent.com/FalixNodes-Software/help-center/main/assets/images/posts/plugins/geysermc/plugin.png">
The path for this image should be `../../../assets/images/posts/plugins/geysermc/plugin.png`. The same things goes for all images throughout the article.

2021-08-08 14:24 UTC, itsjuoum commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +    <a href="https://ci.opencollab.dev//job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar">Download this Plugin</a>
I would change the download link to `https://ci.opencollab.dev//job/GeyserMC/job/Geyser/job/master/` as some people don't have spigot as their server software.

2021-08-08 14:24 UTC, itsjuoum commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +Geyser is a proxy, bridging the gap between Minecraft: Bedrock Edition and Minecraft: Java Edition servers. The ultimate goal of this project is to allow Minecraft: Bedrock Edition users to join Mine
This entire text was copied from `https://geysermc.org/`. Please create your own description for GeyserMC, as we don't want trouble for plagiarizing.

2021-08-08 14:24 UTC, itsjuoum commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +Geyser is a middleware, which translates all the incoming and outgoing packets. With this being said, Geyser works as a standalone proxy, meaning you can use it to join any modern Minecraft Java serv
This entire text was also copied from `https://geysermc.org/`. Please create your own explanation for how GeyserMC works, as we don't want trouble for plagiarizing.

2021-08-08 14:24 UTC, itsjuoum commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +|auth-type:             |Authentication type. Can be offline, online, or [floodgate](https://github.com/GeyserMC/Geyser/wiki/Floodgate), choose "offline" if you want cracked accounts (Tlauncher) to j
I also think that you shouldn't mention other Minecraft clients that allow users to play Minecraft for free. We do not support piracy.

2021-08-08 14:24 UTC, itsjuoum commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +```
I believe the prerequisites would look better in an unordered list. You can achieve this in markdown by using "-".

2021-08-08 14:28 UTC, Mocab commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +    <a href="https://ci.opencollab.dev//job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar">Download this Plugin</a>
This article is mainly for spigot and it's forks, it doesn't matter if it has spigot in its name it works for paper, purpur and other forks aswell

2021-08-08 14:56 UTC, DaddyChimken commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +![Image](https://raw.githubusercontent.com/FalixNodes-Software/help-center/main/assets/images/posts/plugins/geysermc/1.png)
https://github.com/FalixNodes-Software/help-center/pull/38#discussion_r684782595

2021-08-08 19:48 UTC, KorbsStudio commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +tags: Plugins
This needs to be started with a lowercase 'p', please change `Plugins` to `plugins`.

2021-08-09 00:42 UTC, Mocab commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +tags: Plugins
![image](https://user-images.githubusercontent.com/86360684/128650666-00940788-2a9d-45a5-85d6-e10a93c286f2.png)

in the README.md file it shows a capital letter, please change it to a lower case letter.

2021-08-09 00:54 UTC, KorbsStudio commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +tags: Plugins
The article won't show up at all in the help center if you don't use a lowercase p.

2021-08-09 00:58 UTC, Mocab commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +tags: Plugins
I am talking about this https://github.com/FalixNodes-Software/help-center#%EF%B8%8F-metadata

2021-08-09 00:59 UTC, KorbsStudio commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +tags: Plugins
https://github.com/FalixNodes-Software/help-center/blob/main/_posts/minecraft/plugins/2021-06-25-tabs.md#:~:text=Minecraft-,plugins,-/minecraft/plugins/tabs

2021-08-09 01:02 UTC, DaddyChimken requested changes
:D

2021-08-09 01:02 UTC, DaddyChimken commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +6. Go back to the plugins folder, you should see that a new folder was generated, it is usually called "Geyser-Spigot".
```suggestion
6. Go back to the "plugins" folder, you should see that a new folder was generated, it is usually named "Geyser-Spigot".
```

2021-08-09 01:02 UTC, DaddyChimken commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +7. Open it then click on "config.yml".
```suggestion
7. Open the folder and click on "config.yml".
```

2021-08-09 01:02 UTC, DaddyChimken commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +10. Restart your server.
It was always "the server", so to stay consistent, either change everything in this file to "your server" or keep "the server".
```suggestion
10. Restart the server.
```

2021-08-09 01:02 UTC, DaddyChimken commented on _posts/minecraft/plugins/2021-08-08-geysermc.md
> +11. Done! you have successfully set up GeyserMC!
```suggestion
11. Done! You have successfully set up GeyserMC!
```

2021-08-09 01:12 UTC, DaddyChimken approved these changes
lgtm 👍

2021-08-09 01:14 UTC, merged