New post: Server softwares
FalixNodes-Software/help-center pull request #43
Opened 2021-08-22 04:45 UTC by Mocab

will be updated soon to include all other server softwares (bedrock, teamspeak, terraria, etc)

2021-08-22 13:57 UTC, itsjuoum requested changes

2021-08-22 13:57 UTC, itsjuoum commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +permalink: /minecraft/general/server-software/
This is an article that talks about multiple server softwares. I think that the permalink should be `/minecraft/general/server-softwares/`

2021-08-22 13:57 UTC, itsjuoum commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +title:  "Server softwares"
Capitalize the s in "softwares"

2021-08-22 13:57 UTC, itsjuoum commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +# Server softwares
Capitalize the s in "softwares"

2021-08-22 13:57 UTC, itsjuoum commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +
I believe that adding a quick description to this article is important. I came up with:

Choosing your server's software is a very important task. This article will help you choose the software that fits your server's needs.

2021-08-22 13:57 UTC, itsjuoum commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +## 1. PaperMC
There's no need for an ordered list in this article. I think that removing the numeration will help make it look cleaner as well.

2021-08-22 14:00 UTC, itsjuoum commented
I've also noticed that the article name format seems incorrect. It's missing a zero behind the 8 (month). It should look like this: `2021-08-22-server-softwares.md`

2021-08-22 14:01 UTC, Mocab commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +permalink: /minecraft/general/server-software/
We should leave it Minecraft, we can move it once other server softwares are added

2021-08-22 14:02 UTC, Mocab commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +## 1. PaperMC
The numbers in the list correspond to the number in the server setup script

2021-08-22 14:07 UTC, itsjuoum commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +## 1. PaperMC
Ah, understood.

2021-08-22 14:07 UTC, itsjuoum commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +permalink: /minecraft/general/server-software/
I didn't move it from Minecraft, I simply added an s to make it plural.

2021-08-22 14:11 UTC, Mocab commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +permalink: /minecraft/general/server-software/
Oh my bad

2021-08-23 00:43 UTC, DaddyChimken requested changes

2021-08-23 00:43 UTC, DaddyChimken commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +Paper MC is a fork of bukkit and spigot that is optimized and allows you to use plugins, both spigot and bukkit plugins work, It also fixes some Vanilla bugs and exploits!
```suggestion
[PaperMC](https://papermc.io) is a fork of Spigot that is optimized and allows you to use Spigot and Bukkit plugins. It also fixes some Vanilla bugs and exploits!
```

2021-08-23 00:43 UTC, DaddyChimken commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +Purpur is a Fork of Paper and Tuinity that is very optimized, it has many extra features and supports spigot and bukkit plugins. We recommend using this server software.
```suggestion
[Purpur](https://purpur.pl3x.net/) is a Fork of Tuinity that is very optimized. It contains extra features and supports Spigot and Bukkit plugins. We recommend using this server software.
```

2021-08-23 00:43 UTC, DaddyChimken commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +Fabric is a Minecraft software that supports fabric mods and is lightweight.
```suggestion
[Fabric](https://fabricmc.net/) is a lightweight Minecraft software used for Fabric mods.
```

2021-08-23 00:43 UTC, DaddyChimken commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +Vanilla is the default Minecraft software, it does not support plugins or mods.
```suggestion
Vanilla is the default software provided by Minecraft. It does not support plugins or mods.
```

2021-08-23 00:43 UTC, DaddyChimken commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +Vanilla snapshot is the default Minecraft server, it does not support plugins or mods, use this if you want your server's version to be a snapshot.
```suggestion
## 5. Vanilla Snapshot
Vanilla Snapshot is a testing version of Minecraft. Snapshot's usually contain bugs and are not recommended for production use. Just like Vanilla, they do not support plugins or mods.
```

2021-08-23 00:43 UTC, DaddyChimken commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +Tuinity is a fork of Paper that is optimized, it supports spigot and bukkit plugins.
Please remove Tuinity from this list.

All of Tuinity's projects and patches will be merged into Paper.

View the image below from PaperMC's announcement channel:
![image](https://user-images.githubusercontent.com/72452922/130375679-3e0d6b74-1f34-405e-912e-0d714427f718.png)

2021-08-23 00:43 UTC, DaddyChimken commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +Forge is a Minecraft software that supports forge mods.
```suggestion
[Forge](https://files.minecraftforge.net/net/minecraftforge/forge) is a Minecraft software that allows players to use Forge mods.
```

2021-08-23 00:43 UTC, DaddyChimken commented on _posts/minecraft/general/2021-8-22-server-softwares.md
> +Cuberite is a Minecraft server software that is optimized and supports plugins, it does **not** support spigot and bukkit plugins.
```suggestion
[Cuberite](https://cuberite.org/) is an optimized Minecraft server software used for Cuberite plugins.
```

2021-08-23 17:44 UTC, DaddyChimken requested changes

2021-08-23 17:44 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-22-server-softwares.md
> +[PaperMC](https://papermc.io) is a fork of Spigot that is optimized and allows you to use Spigot and Bukkit plugins. It also fixes some Vanilla bugs and exploits!
No need to mention what plugins you can run imo.
If you already mention Paper is a fork of Spigot, then it makes sense you can run Spigot/Bukkit plugins.

```suggestion
[PaperMC](https://papermc.io) is an optimized fork of Spigot that fixes some Vanilla bugs and exploits!
```

2021-08-23 17:44 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-22-server-softwares.md
> +[Purpur](https://purpur.pl3x.net/) is a Fork of Tuinity that is very optimized. It contains extra features and supports Spigot and Bukkit plugins. We recommend using this server software.
```suggestion
[Purpur](https://purpur.pl3x.net/) is an optimized Fork of Tuinity. It contains extra features and supports Spigot and Bukkit plugins. We recommend using this.
```

2021-08-23 17:44 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-22-server-softwares.md
> +[Fabric](https://fabricmc.net/) is a lightweight Minecraft software used for Fabric mods.
```suggestion
## FabricMC
[FabricMC](https://fabricmc.net) is a lightweight Minecraft software used for Fabric mods.
```

2021-08-28 22:02 UTC, DaddyChimken approved these changes

2021-08-29 17:44 UTC, itsjuoum approved these changes

2021-08-30 18:20 UTC, merged