New post: Creating backups
FalixNodes-Software/help-center pull request #45
Opened 2021-08-29 13:56 UTC by Mocab

2021-08-29 17:26 UTC, DaddyChimken commented
Why is this article recommending to archive all your files, rather than using the built in backup system provided by the panel?

2021-08-29 18:06 UTC, itsjuoum commented
I agree with Chimken, it's way easier and faster way of backing up your server files. Although, you need to purchase a backup to be able to create a backup. I think that this article should have both ways of backing up, the easier way, by purchasing a backup, making one, and then downloading it, and the time-consuming one, which is the one already talked about in this article.

2021-08-29 19:03 UTC, DaddyChimken commented
The title of this article is creating backups. It should only be about... creating backups. The official, recommended, and safe thing to use is the backup manager built into the panel. 
The backup manager also comes with more features than a casual 'archive' of your files.

Imo, this article should only be about the backup manager.

2021-08-29 19:16 UTC, itsjuoum commented
You've changed my mind, this article guides you on how to back up your server, and not how to **create** backups.

2021-08-29 21:04 UTC, DaddyChimken commented
What? Creating a backup is backing up your server.

2021-08-29 22:19 UTC, itsjuoum commented
What I meant is that this article didn't explain how to create a backup within ptero panel exclusive option, just explained how to download all your server files.

2021-08-30 00:31 UTC, Mocab commented
Should I rename this guide to `downloading your server files` or just add the other way of backing up?

2021-08-30 00:47 UTC, Mocab commented
We could rename it to uploading/downloading your server files, or we could add both ways of backing up (manually and through the panel)

2021-08-30 02:05 UTC, itsjuoum commented
Downloading and uploading files is an extremely easy task in my opinion, as Ptero's UI is very user friendly. I think there's no need for an article about that.

2021-08-30 02:07 UTC, Mocab commented
well it is very easy but some people dont know how

2021-08-30 02:23 UTC, DaddyChimken commented
> What I meant is that this article didn't explain how to create a backup within ptero panel exclusive option, just explained how to download all your server files.
And I'm saying it should. 
The name itself is "Creating Backups". Not, "how to archive your server files", etc.
If the name was changed, sure. But as it hasn't, it should be about... creating backups.
The panel comes with a tab and page dedicated to managing backups. So why should it be about archiving files with the name "Creating Backups".

2021-08-30 02:26 UTC, itsjuoum commented
Agreed.

2021-08-30 02:32 UTC, DaddyChimken commented
Alright then, as we're now all on the same page. @Mocab please update the PR article to be about the panel's backup manager/page.

2021-08-30 02:33 UTC, Mocab commented
any suggestions on what to rename it to? Ive come up with `managing your server files` but im not sure if its good

2021-08-30 02:34 UTC, Mocab commented
oh wait nvm

2021-08-30 15:32 UTC, itsjuoum requested changes

2021-08-30 15:32 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +title:  "Creating backups"
```suggestion
title:  "Creating Backups"
```

2021-08-30 15:32 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +# How to create backups
```suggestion
# How To Create Backups
```

2021-08-30 15:32 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +
Maybe add a short introduction to this article. I've come up with this:

Backing your server up is a very crucial task when you're a server owner. If anything bad happens to your server, such as griefing or/and unintended actions are performed by you or one of your server operators, you'll be able to revert those changes in your server. In this article, we'll give you a quick and easy explanation on how to create backups for your server within the Game Panel.

2021-08-30 15:32 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +2. Head over to the [panel](https://panel.falixnodes.net).
```suggestion
2. Head over to the [game panel](https://panel.falixnodes.net).
```

2021-08-30 15:32 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +7. You can exclude any files/folders by inserting their name into the "Ignored files & directories" field, you can also use wildcards, refer to the table below to learn how.
```suggestion
7. If needed, you can exclude any files/folders by inserting their name into the "Ignored files & directories" field, you can also use wildcards, refer to the table below to learn how.
```

2021-08-30 15:32 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +> Note: Make sure to type every path/directory/filename/folder name on a separate line
```suggestion
> Note: Make sure to type every path, directory, filename or folder name on a separate line
```

2021-08-30 15:32 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +8. You can choose to lock the backup or leave it unlocked, locking it will prevent the backup from being deleted by a user, you can always unlock it later.
```suggestion
8. You can choose to lock the backup or leave it unlocked, locking it will prevent the backup from being unintentionally deleted by a user, you can always unlock it later.
```

2021-08-30 15:32 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +> Note: You can delete, restore, lock and even download your backup by clicking on the 3 dots to your right!
```suggestion
> Note: You can also delete, restore and download the backup to your device by clicking on the 3 dots to your right!
```

2021-08-31 01:53 UTC, Mocab commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +> Note: You can delete, restore, lock and even download your backup by clicking on the 3 dots to your right!
what about locking / unlocking?

2021-08-31 01:56 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +> Note: You can delete, restore, lock and even download your backup by clicking on the 3 dots to your right!
You already mentioned locking and unlocking on step 8.

2021-08-31 04:32 UTC, DaddyChimken requested changes

2021-08-31 04:32 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +Backing your server up is a very crucial task when you're a server owner. If anything bad happens to your server, such as griefing or/and unintended actions are performed by you or one of your server
```suggestion
Backing up your server is a crucial task when you're a server owner. If anything bad happens to your server, such as griefing and/or unintentional actions, you'll be able to revert those changes in your server. In this article, we'll give you a quick and easy explanation of how to create backups for your server within the Game Panel.
```

2021-08-31 04:32 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +1. Make sure you have allocated backups to your server, you can do so in the [client page](https://client.falixnodes.net).
```suggestion
1. Make sure you have allocated backups to your server, you can do so in the [client panel](https://client.falixnodes.net).
```

2021-08-31 04:32 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +6. Insert a name into the "Backup name".
```suggestion
6. Insert a name into the "Backup name" field.
```

2021-08-31 04:32 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +> Note: Make sure to type every path, directory, filename or folder name on a separate line
```suggestion
> Note: Make sure to type every path, directory, filename or folder name on a separate line.
```

2021-08-31 04:32 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +8. You can choose to lock the backup or leave it unlocked, locking it will prevent the backup from being unintentionally deleted by a user, you can always unlock it later.
```suggestion
8. You can choose to lock the backup, locking it will prevent the backup from being unintentionally deleted by a user, you can always unlock it later.
```

2021-08-31 04:32 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +> Note: You can also delete, restore and download the backup to your device by clicking on the 3 dots to your right!
```suggestion
> Note: You can also delete, restore and download the backup to your device by clicking the 3 dots to the right of the backup!
```

2021-08-31 04:39 UTC, Mocab commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +Backing your server up is a very crucial task when you're a server owner. If anything bad happens to your server, such as griefing or/and unintended actions are performed by you or one of your server
> easy explanation "of" how to create backups for your server within the Game Panel. 

"of" does not sit right with me, "on" is correct in my opinion

2021-08-31 15:51 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +Backing your server up is a very crucial task when you're a server owner. If anything bad happens to your server, such as griefing or/and unintended actions are performed by you or one of your server
That's not what Grammarly says, and I agree with using "of". But really, "on" & "of" can both be used here.

@itsjuoum Your opinion?

2021-08-31 15:59 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +Backing your server up is a very crucial task when you're a server owner. If anything bad happens to your server, such as griefing or/and unintended actions are performed by you or one of your server
When I wrote this and then checked it on Grammarly, I ignored the fact that it should be "of" as "on" sounded good as well. But since Grammarly says that "on" is grammatically incorrect, I think we should change to "of".

2021-08-31 18:33 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +Backing your server up is a very crucial task when you're a server owner. If anything bad happens to your server, such as griefing or/and unintended actions are performed by you or one of your server
👍 

@Mocab Please change it to "of".

2021-09-01 01:41 UTC, DaddyChimken requested changes

2021-09-01 01:41 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +Backing up your server is a crucial task when you're a server owner. If anything bad happens to your server, such as griefing and/or unintentional actions, you'll be able to revert those changes in y
```suggestion
Backing up your server is a crucial task when you're a server owner. If anything bad happens to your server, such as griefing and/or unintentional actions, you'll be able to revert those changes. 
In this article, we'll give you a quick and easy explanation of how to create backups for your server within the Game Panel.
```

2021-09-01 01:41 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-29-creating-backups.md
> +9. Your backup has been created!
```suggestion

That's it! Your backup has been created!
```

2021-09-01 05:07 UTC, DaddyChimken approved these changes

2021-09-02 20:14 UTC, itsjuoum approved these changes

2021-09-02 20:28 UTC, merged