New post: Uploading/Downloading your world file
FalixNodes-Software/help-center pull request #47
Opened 2021-08-31 05:42 UTC by Mocab

2021-09-02 03:41 UTC, DaddyChimken requested changes

2021-09-02 03:41 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +Would you like to upload a world to your server? Great! Follow the guide below to learn how!
```suggestion
This guide explains how to upload a world to your server!
```

2021-09-02 03:41 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +1. Set up your server.
```suggestion
1. Setup your server. You can create servers on the [client panel](https://client.falixnodes.net).
```

2021-09-02 03:41 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +Would you like to download a world from your server? Great! Follow the guide below to learn how!
```suggestion
This guide explains how to download a world from your server!
```

2021-09-02 03:41 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +> Note: If you are using spigot or any of its forks, you should also have `world_nether` and `world_the_end`, these are also your world files so make sure to download them alongside `world`.
```suggestion
> Note: If you are using Spigot or any of its forks, you should also have `world_nether` and `world_the_end`, these are also your world files so make sure to download them alongside `world`.
```

2021-09-02 03:41 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +> Note: If you are using spigot or any of its forks, you should also have `world_nether` and `world_the_end`, these are also your world files so make sure to download them alongside `world`.
@Mocab Doesn't vanilla Minecraft also come with the Nether and End? Or are those world folders named differently?

2021-09-02 07:46 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +> Note: If you are using spigot or any of its forks, you should also have `world_nether` and `world_the_end`, these are also your world files so make sure to download them alongside `world`.
should I add a way to migrate your world from vanilla to spigot...?

2021-09-02 19:15 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +> Note: If you are using spigot or any of its forks, you should also have `world_nether` and `world_the_end`, these are also your world files so make sure to download them alongside `world`.
> Vanilla Minecraft has only 1 world folder, the nether and the end dimensions are merged with the overworld into a single `world` folder, however spigot and its forks have them in separate folders as show in the guide

Ah alright.

2021-09-02 19:16 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +> Note: If you are using spigot or any of its forks, you should also have `world_nether` and `world_the_end`, these are also your world files so make sure to download them alongside `world`.
> should I add a way to migrate your world from vanilla to spigot...?

Imo that isn't in the scope of this article.

2021-09-02 20:24 UTC, itsjuoum requested changes

2021-09-02 20:24 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +title:  "Uploading/Downloading Your World Files"
```suggestion
title:  "Uploading And Downloading Your World Files"
```

2021-09-02 20:24 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +permalink: /minecraft/general/uploading-downloading-your-world-files/
```suggestion
permalink: /minecraft/general/uploading-and-downloading-your-world-files/
```

2021-09-02 20:24 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +1. etup your server. You can create servers on the [client panel](https://client.falixnodes.net).
```suggestion
1. Setup your server. You can create servers on the [client panel](https://client.falixnodes.net).
```

2021-09-02 20:24 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
```suggestion

```

2021-09-02 20:24 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +> Note: Make sure your server is off while following the steps above.
```suggestion

```

2021-09-02 20:24 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +> Note: Make sure your world is archived before following the steps above.
```suggestion

```

2021-09-02 20:24 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +
```suggestion
> Make sure your server is turned off while following the steps below.
> Make sure your world is compressed (in ".zip", ".rar" formats or others) before following the steps below.
```

2021-09-03 02:54 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
Wouldn't it be better to add a break line? it separates both guides.

2021-09-03 19:26 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
Well, imo I think the header (# Downloading Your World) does it

2021-09-03 19:29 UTC, itsjuoum commented
I've also noticed that you forgot an "s" in the article's file name, in the last word.

2021-09-04 01:15 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
![image](https://user-images.githubusercontent.com/86360684/132077650-d085fb30-d9f9-479f-801c-81fca0d9f188.png)

Doesn't look like it, there should be a line above "Managing" but there isn't.

2021-09-04 01:30 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
@Mocab Can you send a screenshot of what it looks like with the 'line'.

2021-09-04 01:34 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
![image](https://user-images.githubusercontent.com/86360684/132078143-e5820817-0d93-4817-ab58-c2209d813b9f.png)

@DaddyChimken

2021-09-04 02:29 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
Thanks!
Imo, I'm fine with either. So I'll let you two discuss.

2021-09-06 15:11 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
Well, "Managing" looks a lot bigger, and it's underlined.

2021-09-07 01:17 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
Please take a look at the screen shots above, I do not see any lines in the first screen shot

2021-09-07 01:33 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
What?

2021-09-07 01:37 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
Do you want to remove the lines?
![image](https://user-images.githubusercontent.com/86360684/132271210-230e5773-4fe5-48d1-bd95-1d7c5b31e011.png)

2021-09-07 01:39 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
As I previsouly said, there's no need to have a line separating as the text formatting already does it job imo.

2021-09-07 01:44 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
@KorbsStudio what do you think? should we add a line to separate the download and upload guides?

2021-09-07 02:11 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-file.md
> +---------------------------------------------------------
This discussion is taking way longer than it should be.

I'll give my input, please remove the line. The title markdown (`#`) already separates the sections enough.

2021-09-07 03:03 UTC, DaddyChimken requested changes

2021-09-07 03:03 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +> Make sure your world is compressed (in ".zip", ".rar" formats or others) before following the steps below.
```suggestion
> Make sure your world is compressed/archived (ending in ".zip", ".rar" or others) before following the steps below.
```

2021-09-07 03:03 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +5. Check the boxes to the left of your world folders.
> Locate your world folder, it is usually called `world`.

Here it's saying one world folder, while
> Check the boxes to the left of your world folders.

here it's saying multiple world folders.


Please stick with one or the other.

2021-09-07 22:24 UTC, DaddyChimken requested changes

2021-09-07 22:24 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +5. Check the boxes to the left of your world folder.
There is only one box next to a file, from what I see. What "boxes" are you talking about here?

Additionally, since you changed it to one folder, you can directly right click and hit "Archive".

2021-09-09 09:23 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +5. Check the boxes to the left of your world folder.
The "archive" popup only appears once you select a file

2021-09-10 01:02 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +5. Check the boxes to the left of your world folder.
Right click --> "Archive"?

2021-09-10 01:05 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +5. Check the boxes to the left of your world folder.
doesn't it do the same thing? plus its easier to show in images.

2021-09-10 03:10 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +5. Check the boxes to the left of your world folder.
It's easier to simply right click the file.

2021-09-10 03:19 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +5. Check the boxes to the left of your world folder.
how do I show it in the screen shot?

2021-09-10 21:58 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +5. Check the boxes to the left of your world folder.
You don't need to use a screenshot, but I'd just say something like "right click file and click 'archive'" then show a screenshot of the Archive button.

This is just my opinion, do whatever you feel is best.

2021-09-11 02:31 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +5. Check the boxes to the left of your world folder.
In my opinion, I think using the box is better, for 2 reasons:
1- you can select multiple worlds,  (if you have more than one)
2- its easier to explain and show

2021-09-11 04:14 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +5. Check the boxes to the left of your world folder.
1. In your example, you stated one world. in addition, I've stated above to either set the example to multiple worlds or stick with one.
2. How? What's the point of clicking the tiny box next to the file and looking at the bottom of the page just to hit "Archive". I don't see how this is easier than simply right clicking the file.

2021-09-11 04:20 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +5. Check the boxes to the left of your world folder.
some servers might have multiple worlds as stated in the "note", should I go with multiple worlds for this guide?

2021-09-11 04:48 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +5. Check the boxes to the left of your world folder.
Entirely up to you, but really, there isn't a difference from using the boxes or just right clicking each file if you're downloading multiple worlds.

2021-09-12 21:41 UTC, DaddyChimken requested changes

2021-09-12 21:41 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +9. Your world(s) folder should be downloaded!
The article name and section titles all state downloading **a** world (downloading **1** world).

Either change **everything**, or stick to one, which I recommend.

2021-09-13 01:03 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +9. Your world(s) folder should be downloaded!
the issue is that if I use only one world, users with multiple worlds might get confused

2021-09-13 01:40 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +9. Your world(s) folder should be downloaded!
They can do the exact same for each world, that isn't confusing.

2021-09-13 17:04 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +9. Your world(s) folder should be downloaded!
> 
> 
> They can do the exact same for each world, that isn't confusing.

Exactly.

2021-09-15 01:44 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +8. Click on "unarchive".
```suggestion
8. Click on "Unarchive".
```

2021-09-15 01:44 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-Uploading-downloading-your-world-files.md
> +9. Your world folder should be downloaded!
```suggestion
5. Click on the 3 dots to the right of the folder.
6. Click on "Archive".
7. A new file should be created, locate it and click on the 3 dots to its right.
8. Click on "Download".
9. Your world folder should be downloaded!
```

2021-09-15 22:20 UTC, DaddyChimken approved these changes

2021-09-16 12:47 UTC, itsjuoum approved these changes

2021-09-16 12:48 UTC, merged