Update 2021-08-31-getting-started.md
FalixNodes-Software/help-center pull request #49
Opened 2021-09-04 12:39 UTC by Mocab

This guide might be outdated, I am planning to separate this guide into multiple guides/categories in the near future. It will be updated by then.

2021-09-04 13:01 UTC, DaddyChimken requested changes

2021-09-04 13:01 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +5. Start your server and you are done!
Just telling the user to paste in something from a website and starting their server isn't something I want to do.
If you're going to add in something about startup flags, could you at least explain what each flag does, or explain what all the startup flags combined will do to the server.

I'm also fine with separating this to a new article.

2021-09-04 13:22 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +5. Start your server and you are done!
> I'm also fine with separating this to a new article.

Do you think its a good idea to sort it like this?
/minecraft/startup/java-arguments

2021-09-04 13:25 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +5. Start your server and you are done!
Not sure myself. @itsjuoum ^^

2021-09-04 13:26 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +5. Start your server and you are done!
ive been brainstorming for a while, but i cant come up with a better one

2021-09-04 20:35 UTC, KorbsStudio commented
At least change the file name from **2021-08-31-getting-started.md** to **2021-09-04-getting-started.md**

2021-09-04 23:03 UTC, Mocab commented
> At least change the file name from **2021-08-31-getting-started.md** to **2021-09-04-getting-started.md**

As I said above, I have not updated the guide other than the java flags, I will rename it once it has been updated.

2021-09-06 15:14 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +5. Start your server and you are done!
Yeah, I think that it's better if we separate this to a new article

2021-09-07 01:26 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +5. Start your server and you are done!
What should the permalink be?

2021-09-07 01:32 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +5. Start your server and you are done!
This isn't a discussion for that article, focus on this one first.

2021-09-08 08:35 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +
There are some typos here, but I'm also unsure if this info is correct. @DaddyChimken can you please confirm?

2021-09-08 14:02 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +
"it pre processes the memory to be more usable"

No one will understand this, please fix the grammar and add more information while making it easier to understand.

2021-09-09 01:12 UTC, DaddyChimken requested changes

2021-09-09 01:12 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +The flags optimize the ram to be more efficient.
What flags are you talking about? How does it "optimize the ram"? How does using these flags make my server more "efficient"?

2021-09-09 14:34 UTC, itsjuoum requested changes

2021-09-09 14:34 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +> What does the flags do?
```suggestion
> What do the flags do? 
```

2021-09-09 14:34 UTC, itsjuoum commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +You can find a detailed guide on [aikar's website](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/).
I don't think that naming another person's website is a good thing to do. That website also takes a [bunch of time to load](https://i.imgur.com/avDbOvb.png).

2021-09-09 14:50 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +You can find a detailed guide on [aikar's website](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/).
I'll rename it to something else, as for the second issue, nothing I can do about, I am not a java Dev so I don't know what flags do in detail

2021-09-10 00:59 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +You can find a detailed guide [here](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/).
```suggestion
These flags help keep your server run with a stable TPS and without any large garbage collection spikes by tweaking different allocation and garbage collection settings for Minecraft. 
For further information on the flags, check out [this blog](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft).
```
Made this pretty quickly, feel free to correct any grammar mistakes.

2021-09-10 03:07 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +You can find a detailed guide [here](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/).
Now that I've re-read my suggestion, it sounds a bit off. I'll see if I can make any improvements tomorrow.

2021-09-10 06:43 UTC, KorbsStudio commented
Heads up, this article was recently updated on my end for the Bedrock Edition.

2021-09-11 17:34 UTC, DaddyChimken requested changes

2021-09-11 17:34 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +For further information on the flags, check out [this blog](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft).
```suggestion
> Why should I use these startup flags? 
These flags help keep your server run with a stable TPS and without any large garbage collection spikes by tweaking different allocation and garbage collection settings for Minecraft. 
For further information on these flags, check out [this blog](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft).
```

2021-09-14 01:43 UTC, DaddyChimken requested changes

2021-09-14 01:43 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +These flags help keep your server run with a stable TPS and without any large garbage collection spikes by tweaking different allocation and garbage collection settings for Minecraft.
```suggestion
These flags help keep your server running with a stable TPS and without any large garbage collection spikes by tweaking different allocation and garbage collection settings for Minecraft. 
```

2021-09-14 01:44 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +These flags help keep your server run with a stable TPS and without any large garbage collection spikes by tweaking different allocation and garbage collection settings for Minecraft.
Actually, nvm.

2021-09-14 01:46 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +These flags help keep your server run with a stable TPS and without any large garbage collection spikes by tweaking different allocation and garbage collection settings for Minecraft.
```suggestion
These flags help your server run with a stable TPS and without any large garbage collection spikes by tweaking different allocation and garbage collection settings for Minecraft. 
```

2021-09-14 01:47 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +These flags help keep your server run with a stable TPS and without any large garbage collection spikes by tweaking different allocation and garbage collection settings for Minecraft.
This still seems a bit wordy and big imo, anyone have any suggestions?

2021-09-14 02:14 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +These flags help keep your server run with a stable TPS and without any large garbage collection spikes by tweaking different allocation and garbage collection settings for Minecraft.
cant be helped ¯\_(ツ)_/¯

2021-09-14 02:17 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +These flags help keep your server run with a stable TPS and without any large garbage collection spikes by tweaking different allocation and garbage collection settings for Minecraft.
The sentence is super long with 2 "ands", which also makes it wordy and confusing to understand. 
*I also made this sentence in ~5 minutes, it definitely should be at least edited.*

2021-09-14 02:23 UTC, Mocab commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +These flags help keep your server run with a stable TPS and without any large garbage collection spikes by tweaking different allocation and garbage collection settings for Minecraft.
We should remove ` and without any large garbage collection spikes` , im pretty sure most users don't know what it is, plus its the part of sentence that's confusing.

2021-09-15 01:38 UTC, DaddyChimken commented on _posts/minecraft/general/2021-08-31-getting-started.md
> +These flags help keep your server run with a stable TPS and without any large garbage collection spikes by tweaking different allocation and garbage collection settings for Minecraft.
Sure, I'm fine with that.

```suggestion
These flags help keep your server run with a stable TPS by tweaking different allocation and garbage collection settings for Minecraft. 
```

2021-09-15 22:22 UTC, DaddyChimken commented
Please rebase, there are merge conflicts.

2021-09-17 06:55 UTC, Mocab commented
I hope I did it correctly 😅

2021-09-17 21:25 UTC, KorbsStudio commented
There are no longer conflicts with this PR, will merge once approved.

2021-09-18 01:53 UTC, Mocab commented
Ill close this pull request and start again, since this place is a mess

2021-09-18 01:53 UTC, closed without merging