Edit: Buying Items from the Store
FalixNodes-Software/help-center pull request #50
Opened 2021-09-05 12:01 UTC by Mocab

2021-09-05 18:58 UTC, DaddyChimken requested changes

2021-09-05 18:58 UTC, DaddyChimken commented on _posts/falix/general/2021-09-05-store.md
> +2. Click on "[Coins](https://client.falixnodes.net/coins)" at the top left of the page.
```suggestion
2. Click on "[... FalixCoins](https://client.falixnodes.net/coins)" at the top left of the page.
```
Or something. There isn't any button named "Coins" from what I see. Only the amount of FalixCoins you have.

2021-09-05 18:58 UTC, DaddyChimken commented on _posts/falix/general/2021-09-05-store.md
> +3. Click on "[Resource store](https://client.falixnodes.net/store)" at the right side of the page.
```suggestion
3. Click on "[Resources Store](https://client.falixnodes.net/store)" at the right side of the page.
```
Please actually set values in quotes to the exact value they represent.
![image](https://user-images.githubusercontent.com/72452922/132138348-d1abaa13-911b-46c9-a5cf-51867071a03e.png)

2021-09-06 15:15 UTC, itsjuoum approved these changes

2021-09-06 16:45 UTC, DaddyChimken approved these changes
Some screenshots might be useful, otherwise lgtm

2021-09-07 22:20 UTC, DaddyChimken approved these changes

2021-09-08 08:31 UTC, itsjuoum approved these changes

2021-09-08 08:31 UTC, merged