Update overlay
FalixNodes-Software/help-center pull request #52
Opened 2021-09-05 17:25 UTC by HellCat46

2021-09-05 18:54 UTC, DaddyChimken commented
Please separate Java edition softwares and Bedrock edition softwares, a different section is fine by me.
This way, user's will know which software is for which edition.

2021-09-05 23:16 UTC, Mocab commented
1. Please rename this pull request to `edit: server softwares`.
![image](https://user-images.githubusercontent.com/86360684/132143957-9d113c6d-7397-449e-826f-d179a568fb4f.png)

2. Update the file name to `2021-9-6-server-softwares.md` , every time you edit a post you must update the date in its name.

2021-09-05 23:49 UTC, Mocab requested changes

2021-09-05 23:49 UTC, Mocab commented on _posts/minecraft/general/2021-08-22-server-softwares.md
> +[Pocketmine](https://pmmp.readthedocs.io/en/rtfd/installation.html) is a lightweight Minecraft Bedrock server software. It does support plugins and Multi world System.
```suggestion
[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and Multi world Systems.
```

2021-09-05 23:49 UTC, Mocab commented on _posts/minecraft/general/2021-08-22-server-softwares.md
> +Vanilla Bedrock is the default Bedrock software provided by Minecraft. It does support Behaviour packs but not plugins.
```suggestion
Vanilla Bedrock is the default Bedrock software provided by Minecraft. It supports Behaviour packs but not plugins.
```

2021-09-06 03:11 UTC, HellCat46 commented on _posts/minecraft/general/2021-08-22-server-softwares.md
> +[Pocketmine](https://pmmp.readthedocs.io/en/rtfd/installation.html) is a lightweight Minecraft Bedrock server software. It does support plugins and Multi world System.
Done

2021-09-06 05:52 UTC, Mocab commented on _posts/minecraft/general/2021-08-22-server-softwares.md
> +[Pocketmine](https://pmmp.readthedocs.io/en/rtfd/installation.html) is a lightweight Minecraft Bedrock server software. It does support plugins and Multi world System.
you do not have to say done, just mark this as resolved

2021-09-06 16:48 UTC, DaddyChimken requested changes

2021-09-06 16:48 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and Multi world Systems.
> Multi world Systems.

Why are "multi" and "systems" capitalized?

2021-09-06 16:48 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +Altay is an optimized fork of Pocketmine(PMMP). It contains many extra features and supports all Pocketmine plugins.
```suggestion
Altay is an optimized fork of Pocketmine(PMMP). It contains extra features and supports Pocketmine plugins.
```

2021-09-06 16:56 UTC, HellCat46 commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and Multi world Systems.
Because I want to highlight those word but I will going to change "Multi world" to "Multiworld" tomorrow.

2021-09-06 17:51 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and Multi world Systems.
Capitalizing a word just to "highlight" is incorrect grammar.
If you really wanted to "highlight" it, just bold it with markdown.

2021-09-07 01:15 UTC, HellCat46 commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and Multi world Systems.
Ok so Which one is better according to you "Multiworld system" or "multiworld system".

2021-09-07 01:21 UTC, Mocab commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and Multi world Systems.
use `multiworld system`

2021-09-07 02:13 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and Multi world Systems.
> Ok so Which one is better according to you "Multiworld system" or "multiworld system".

Whichever one is correct grammar.

2021-09-07 04:37 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +
Whats with this?

2021-09-07 05:34 UTC, HellCat46 commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +
![Space](https://user-images.githubusercontent.com/78464152/132289153-e08c2e38-ac84-4634-8197-0aeb67d9de9f.png) this space and line are dividing Java and Bedrock. In my opinion, this is looking good.

2021-09-07 05:36 UTC, HellCat46 commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +
![Withoutspace](https://user-images.githubusercontent.com/78464152/132289711-fb90c2c8-aec9-4cc1-bbe7-745db0a781ca.png)
Without that space and line, it will be going to look like this

2021-09-07 13:37 UTC, itsjuoum commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +
Imo, remove the line and keep the line break (<br>)

2021-09-07 15:43 UTC, HellCat46 commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +
![Better](https://user-images.githubusercontent.com/78464152/132373509-7dcbc320-0e04-4f1a-bc94-6160dcbbef36.png)
Like this?

2021-09-08 03:45 UTC, DaddyChimken requested changes

2021-09-08 03:45 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +Altay is an optimized fork of Pocketmine(PMMP). It contains extra features and supports Pocketmine plugins.
```suggestion
[Altay](https://github.com/TuranicTeam/Altay) is an optimized fork of Pocketmine that contains extra features and supports all Pocketmine plugins.
```

2021-09-08 03:45 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +Vanilla Bedrock is the default Bedrock software provided by Minecraft. It supports Behaviour packs but not plugins.
```suggestion
Vanilla Bedrock is the default Bedrock software provided by Minecraft. It does not support plugins.
```

Behaviour packs are default with Vanilla Bedrock.

2021-09-08 03:49 UTC, DaddyChimken commented
Is it on purpose that the Bedrock section only has two server softwares?
How about softwares such as Nukkit, BlueLight, Tesseract, etc.

I don't use Minecraft Bedrock Edition so please let me know if the example softwares I listed are not recommended, unstable, or no longer maintained.

2021-09-08 04:04 UTC, HellCat46 commented
> Is it on purpose that the Bedrock section only has two server softwares?
> How about softwares such as Nukkit, BlueLight, Tesseract, etc.
> 
> I don't use Minecraft Bedrock Edition so please let me know if the example softwares I listed are not recommended, unstable, or no longer maintained.

FalixNodes only supports Altay, Pocketmine, Vanilla Bedrock and Cloudburst. Since FalixNodes doesn't support Softwares like Blue light, Tesseract and there is no way customers can use them on FalixNodes. I don't think We have to add them. I will going to add Cloudburst and more information about server software like They are recommended or not. Also if they do recommend then in which case they are recommended.

2021-09-08 04:13 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +### Pocketmine(PMMP)
```suggestion
### Pocketmine (PMMP)
```

2021-09-08 14:03 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and multiworld system.
> and multiworld system.

What is a "multiworld system"?

2021-09-08 14:17 UTC, HellCat46 commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and multiworld system.
You can use many worlds in one server and you can switch from one world to another world using in-game commands.

2021-09-08 15:55 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and multiworld system.
Is this default with Pocketmine or do you need to install some sort of plugin?
If its default with Pocketmine, any docs/guides you can link?

2021-09-09 00:52 UTC, HellCat46 commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and multiworld system.
You will need to install a plugin (Multiworld).

2021-09-09 01:10 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and multiworld system.
Then please remove this. You already stated Pocketmine supports plugins.
```suggestion
[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software that supports Pocketmine plugins.
```

2021-09-09 01:13 UTC, HellCat46 commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and multiworld system.
Ok. also "Pocketmine plugins" is correct? Because we are talking about pocketmine in that whole paragraph. Should I Remove "Pocketmine".

2021-09-09 01:26 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Pocketmine](https://www.pocketmine.net) is a lightweight Minecraft Bedrock server software. It supports Pocketmine plugins and multiworld system.
I'm fine either way. You can keep the "Pocketmine plugins".

2021-09-10 01:03 UTC, DaddyChimken requested changes

2021-09-10 01:03 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Altay](https://github.com/TuranicTeam/Altay) is an optimized fork of Pocketmine that contains extra features and supports all Pocketmine plugins.
```suggestion
[Altay](https://github.com/TuranicTeam/Altay) is an optimized fork of Pocketmine that contains extra features and supports Pocketmine plugins.
```

2021-09-10 03:05 UTC, DaddyChimken commented on _posts/minecraft/general/2021-09-06-server-softwares.md
> +[Cloudburst](https://cloudburstmc.org/) is an optimized fork of Cloudburst Nukkit written in Java that supports Nukkit plugins.
```suggestion
[CloudburstMC](https://cloudburstmc.org) (aka NukkitX) is an optimized fork of Nukkit that supports Nukkit plugins.
```

2021-09-10 03:11 UTC, DaddyChimken approved these changes
lgtm (finally 😅 )

2021-09-10 06:34 UTC, merged