Edit: account management
FalixNodes-Software/help-center pull request #54
Opened 2021-09-09 13:33 UTC by Mocab

2021-09-09 14:22 UTC, itsjuoum requested changes

2021-09-09 14:22 UTC, itsjuoum commented on _posts/falix/general/2021-08-04-account-management.md
> +If you've forgotten your account's password for your Game Panel, please click on your profile picture in the [client page](client.falixnodes.net/) then click on "[settings](https://client.falixnodes.
```suggestion
If you've forgotten your account's password for your Game Panel, please click on your profile picture in the [client page](client.falixnodes.net/) then click on "[Settings](https://client.falixnodes.net/profile/settings)", it should be at the top right corner of your screen. You should be redirected to another page. Scroll down and click on "Change Game Panel Password". You will be redirected back to the main page, scroll down and you should see an alert containing your password.
```

2021-09-09 14:22 UTC, itsjuoum commented on _posts/falix/general/2021-08-04-account-management.md
> +![image](../../../assets/images/posts/falix/account-management/1.png)
Naming an image "1" is not a good practice. The file name should be about what the image is. Something like "password-alert-box.png"

2021-09-10 00:49 UTC, DaddyChimken requested changes

2021-09-10 00:49 UTC, DaddyChimken commented on _posts/falix/general/2021-08-04-account-management.md
> +If you've forgotten your account's password for your Game Panel, please click on your profile picture in the [Client Page](client.falixnodes.net/) then click on "[Settings](https://client.falixnodes.
```suggestion
If you've forgotten your account's password for the Game Panel, click on your profile picture in the top right corner of your screen on the [Client Page](client.falixnodes.net/), then click on "[Settings](https://client.falixnodes.net/profile/settings)". You should be redirected to another page. 
Scroll down and click on "Change Game Panel Password". You will be redirected back to the main page, scroll down and you should see a success alert containing your password.
```

2021-09-10 03:09 UTC, DaddyChimken requested changes

2021-09-10 03:09 UTC, DaddyChimken commented on _posts/falix/general/2021-08-04-account-management.md
> +If you've forgotten your account's password for the Game Panel, click on your profile picture in the top right corner of your screen on the [Client Page](client.falixnodes.net/), then click on "[Sett
The client & panel site are both panels. Please remember this.

```suggestion
If you've forgotten your account's password for the Game Panel, click on your profile picture in the top right corner of your screen on the [Client Panel](client.falixnodes.net/), then click on "[Settings](https://client.falixnodes.net/profile/settings)". You should be redirected to another page. 
```

2021-09-10 22:00 UTC, DaddyChimken approved these changes

2021-09-13 01:07 UTC, merged