Edit: Getting coins
FalixNodes-Software/help-center pull request #55
Opened 2021-09-09 13:43 UTC by Mocab

2021-09-09 14:24 UTC, itsjuoum requested changes

2021-09-09 14:24 UTC, itsjuoum commented on _posts/falix/general/2021-08-10-getting-coins.md
> +Do note that you must log out and login to recieve your coins.
```suggestion
Note that you must log out and log back in to receive your coins.
```

2021-09-10 01:01 UTC, DaddyChimken commented
Wasn't a "Refresh Guilds" (or something similar) button added? Thus making logging out unnecessary.

2021-09-10 01:07 UTC, Mocab commented
> Wasn't a "Refresh Guilds" (or something similar) button added? Thus making logging out unnecessary.

I do not remember seeing it anywhere, I will double check after a while

2021-09-11 04:12 UTC, DaddyChimken requested changes

2021-09-11 04:12 UTC, DaddyChimken commented on _posts/falix/general/2021-08-10-getting-coins.md
> +To receive your coins for joining servers, Click on "[Get FalixCoins for joined servers](https://client.falixnodes.net/updatejoinedservers)", in the join for resources page.
```suggestion
To receive your FalixCoins from joining promoted servers, Click on "[Get FalixCoins for joined servers](https://client.falixnodes.net/updatejoinedservers)", in the join for resources page.
```

Please also add a hyperlink to the join for resources page.

2021-09-12 21:39 UTC, DaddyChimken commented on _posts/falix/general/2021-08-10-getting-coins.md
> +To receive your FalixCoins from joining promoted servers, Click on "[Get FalixCoins for joined servers](https://client.falixnodes.net/updatejoinedservers)", in the [join for resources page](https://c
```suggestion
To receive your FalixCoins from joining promoted servers, Click on "[Get FalixCoins for joined servers](https://client.falixnodes.net/updatejoinedservers)", in the [join for rewards page](https://client.falixnodes.net/join_for_rewards).
```

2021-09-13 01:41 UTC, DaddyChimken approved these changes

2021-09-13 17:02 UTC, itsjuoum approved these changes

2021-09-13 17:02 UTC, merged