Edit: Getting-coins
FalixNodes-Software/help-center pull request #61
Opened 2021-09-20 03:36 UTC by Mocab

2021-09-20 23:31 UTC, DaddyChimken commented on _posts/falix/general/2021-09-20-getting-coins.md
> +There are currently two ways of getting coins, you can find them [here](https://client.falixnodes.net/coins)
```suggestion
There are currently two ways of getting coins, you can find them [here](https://client.falixnodes.net/coins).
```

2021-09-20 23:31 UTC, DaddyChimken commented on _posts/falix/general/2021-09-20-getting-coins.md
> +3. Copy your discord ID, follow [this](https://www.remote.tools/remote-work/how-to-find-discord-id) guide to learn how.
Either change this hyperlink to the "Account Management" article, or the Discord support article https://support.discord.com/hc/en-us/articles/206346498.

2021-09-20 23:31 UTC, DaddyChimken commented on _posts/falix/general/2021-09-20-getting-coins.md
> +If you do not see any ads, try again later
```suggestion
If you do not see any ads, try again later.
```

2021-09-22 19:52 UTC, DaddyChimken commented on _posts/falix/general/2021-09-20-getting-coins.md
> +3. Copy your discord ID, follow [this](https://support.discord.com/hc/en-us/articles/206346498) guide to learn how.
```suggestion
3. Copy your Discord user ID, follow [this](https://support.discord.com/hc/en-us/articles/206346498) guide to learn how.
```

2021-09-22 19:52 UTC, DaddyChimken commented on _posts/falix/general/2021-09-20-getting-coins.md
> +4. Open the app and insert your discord ID into the field given.
```suggestion
4. Open the app and insert your discord user ID into the given field.
```

2021-09-25 04:24 UTC, DaddyChimken approved these changes

2021-09-25 11:01 UTC, itsjuoum requested changes

2021-10-03 17:13 UTC, itsjuoum approved these changes

2021-10-03 17:13 UTC, merged