New post: Adding users to your server
FalixNodes-Software/help-center pull request #66
Opened 2021-09-24 03:54 UTC by Mocab

2021-09-25 11:04 UTC, itsjuoum commented
"Adding users to your server" makes it look like you're going to explain how to make users join your server, imo. "Giving users access to your server panel" or something similar would be better,

2021-10-01 01:06 UTC, DaddyChimken requested changes

2021-10-01 01:06 UTC, DaddyChimken commented on _posts/falix/general/2021-09-24-adding-users-to-your-server.md
> +If you need to give other users access to your panel, you can easily do so using the "users" feature in the game panel, follow the steps below to learn how:
```suggestion
If you need to give other users access to your server panel, you can easily do so using the "users" feature in the game panel, follow the steps below to learn how:
```

2021-10-01 01:06 UTC, DaddyChimken commented on _posts/falix/general/2021-09-24-adding-users-to-your-server.md
> +> Note: Make sure the user you are adding is already registered in Falix.
```suggestion
> Note: Make sure the user you are adding is already registered in Falix, otherwise this will not work.
```

2021-10-01 01:06 UTC, DaddyChimken commented on _posts/falix/general/2021-09-24-adding-users-to-your-server.md
> +1. Go to the [Game Panel](https://panel.falixnodes.net) and click on any server you want.
```suggestion
1. Go to the [Game Panel](https://panel.falixnodes.net) and click on your server.
```

2021-10-01 01:06 UTC, DaddyChimken commented on _posts/falix/general/2021-09-24-adding-users-to-your-server.md
> +2. Click on "Users" at the top of the page.
```suggestion
2. Click on the "Users" tab at the top of the page.
```

2021-10-02 02:36 UTC, DaddyChimken approved these changes

2021-10-02 18:19 UTC, merged