New Post: Installing Plugins
FalixNodes-Software/help-center pull request #7
Opened 2021-03-25 01:50 UTC by MrTronMan

2021-03-25 02:09 UTC, KorbsStudio commented
This shouldn't start out with:
```
<h1 id="getting-started-with-plugins">Getting started with plugins</h1>
```
Since the title belongs in the sidebar of the article, although I liked that you used an ID for links and such.

Also, other areas of the sidebar need to be edited (Report, Edit, etc).

Also, I think we can more informational, like fully explaining why users shouldn't have the server running while installing new plugins. Also, explain why users should restart instead of reloading(as this can break plugins like DiscordSRV).
I want our help center to provide as much information as possible, even if it's a lot! 

Also during this update of our help center, we'll like to correct our grammar, I have been using Grammarly for this:
![image](https://i.imgur.com/zA1cbJT.png)

2021-03-25 14:23 UTC, MrTronMan commented
I have renamed it to plugins instead of installing plugins because this is all about plugins now 😄 

I have added more detail such as a way to turn off the plugin without deleting it. I have also added details on why you should turn off the server and also not reload, I have also moved that more toward the top.

2021-03-25 14:34 UTC, KorbsStudio requested changes
For **Turning off a plugin** and **Turning back on the plugin**, they should both be changed to `<h3>` instead of `<h2>` and should be put under a `<h2>` title called **Enabling and Disabling Plugins**. Of course, changing both of the `<h3>` titles to **Enabling** and **Disabling**.

Example:
# Enabling and Disabling
## Enabling
## Disabling
__ 
Add explanation behind what a YML file is for **Configuration**.

A list of recommendations for plugins might be added in the future, providing alternatives.

2021-03-25 15:57 UTC, MrTronMan commented
**Updated the plugins.html**

Added, what you said. Added an explanation on `YMLs` (YAMLS). Also decided to rename some of the headings.

2021-03-26 05:44 UTC, KylePlays-Studio commented
this falix trash yeet polarnodes better than falixnodes yeet

2021-03-26 16:16 UTC, MrTronMan reviewed
Updated the plugins.html

Added, what you said. Added an explanation on YMLs (YAMLS). Also decided to rename some of the headings.

2021-03-28 00:18 UTC, KorbsStudio commented on article/minecraft/general/plugins/index.html
> +                <p id="category">Minecraft General/p>
Syntax error

2021-03-28 04:27 UTC, MrTronMan reviewed
Moved file locations, as well as I, fixed the syntax error.

2021-03-28 08:41 UTC, KylePlays-Studio commented
stfu dis surver suks

2021-03-28 08:41 UTC, KylePlays-Studio commented
stfu dis surver suks

2021-03-28 08:41 UTC, KylePlays-Studio commented
stfu dis surver suks

2021-03-28 08:41 UTC, KylePlays-Studio commented
stfu dis surver suks

2021-03-28 08:41 UTC, KylePlays-Studio commented
stfu dis surver suks

2021-03-28 08:41 UTC, KylePlays-Studio commented
stfu dis surver suks

2021-03-31 12:25 UTC, MrTronMan commented
Added more about the plugin server jars, where to get plugin server jars.

2021-04-08 01:43 UTC, MrTronMan commented
You did a revamp and changed it to Markdown so I will convert and update the repository.

2021-04-08 01:43 UTC, closed without merging