Edit: Uploading-downloading-your-world-files
FalixNodes-Software/help-center pull request #74
Opened 2021-10-20 18:33 UTC by HellCat46

2021-10-30 17:37 UTC, DaddyChimken requested changes

2021-10-30 17:37 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +1. Open file explorer of your device.
```suggestion
1. Open any type of file explorer application on your device.
```

2021-10-30 17:37 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +                 <td>here 'username' is your own windows username.</td>
```suggestion
                 <td>PC (Windows 10 Edition)</td>
                 <td>\Users\USERNAME\AppData\Local\Packages\
                     Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang
                     \minecraftWorlds\
                 </td>
                 <td>"USERNAME" is your own Windows username.</td>
```

2021-10-30 17:37 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +     </table>
Is it possible to use inline codeblocks for the file paths? Imo it'll look better.

2021-10-30 17:37 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +3. There will be a folder (or multiple folders, one for each world you have in the Win 10 edition/pocket edition) with a random name like "BQUAAIFxEAA=", find the one that is the world you want to pu
```suggestion
3. There will be a folder (or multiple folders, one for each world if you have Windows 10 Edition or Pocket Edition) with a random name like "BQUAAIFxEAA=", find the world file you want to put on your dedicated server by checking `levelname.txt`.
```

2021-10-30 17:37 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +7. Navigate to the `worlds` folder, open it.
```suggestion
7. Navigate to the `worlds` folder and open it.
```

2021-10-30 17:37 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +12. Remove `=` symbol from the folder name.
```suggestion
12. Remove the `=` symbol from the world folder name by clicking the "Rename" button from the 3 dots.
```

2021-10-30 17:37 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +12. Open server.properties file on your bedrock server, find the 'level-name=' line and enter the name of the folder you uploaded in step 8 here (spaces are allowed) so that it looks something like `
```suggestion
12. Open the `server.properties` file on your Bedrock server. Find the `level-name=` line and enter the name of the folder you uploaded in step 8, (spaces are allowed) so that it looks something like `level-name=My Server Level`. This must match the folder name.
```

2021-10-30 17:37 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +13. Start your bedrock server, and it should now have your imported world running.
```suggestion
13. Start your Bedrock server. It should now be running your imported world.
```

2021-11-03 03:13 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +Apps/com.mojang.minecraftpe/Documents/games/com.mojang/minecraftWorlds\
Are these supposed to have a `\` at the end?

2021-11-03 04:11 UTC, HellCat46 commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +Apps/com.mojang.minecraftpe/Documents/games/com.mojang/minecraftWorlds\
I am supposed to use `/` instead of `\` because world folders are located in the "minecraftWorlds" Folder. I will fix that when I will able to. (maybe after 4-5 hours)

2021-11-03 07:55 UTC, HellCat46 commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +Apps/com.mojang.minecraftpe/Documents/games/com.mojang/minecraftWorlds\
nvm
I removed slash and backslash from the end of paths.

2021-11-08 01:17 UTC, Darker-Ink requested changes

2021-11-08 02:39 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +> Note: "USERNAME" is your own Windows username. <br>
It honestly doesn't matter. Its simply there as a placeholder and is also clarified below to replace it.
Although I have no problem with using `%USERNAME%` anyways. Up to @HellCat46.

2021-11-08 02:41 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +This guide explains how to upload a world to your Bedrock server!
Since this is under the Bedrock section, there is no need to mention the type of server. This is already the same for the Java section.
```suggestion
This guide explains how to upload a world to your server!
```

2021-11-08 02:41 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +This guide explains how to download a world from your Bedrock server!
ditto
```suggestion
This guide explains how to download a world from your server!
```

2021-11-08 10:40 UTC, HellCat46 commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +> Note: "USERNAME" is your own Windows username. <br>
I agree with @DaddyChimken. I don't think we need to explain more about the "USERNAME" placeholder

2021-11-08 10:53 UTC, HellCat46 commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +This guide explains how to upload a world to your Bedrock server!
Should I use only `server` in steps too?

2021-11-08 21:21 UTC, DaddyChimken commented on _posts/minecraft/general/2021-10-20-Uploading-downloading-your-world-files.md
> +This guide explains how to upload a world to your Bedrock server!
Sure.

2021-11-17 22:16 UTC, DaddyChimken approved these changes

2021-11-20 03:24 UTC, closed without merging