New post: dynmap
FalixNodes-Software/help-center pull request #89
Opened 2021-12-28 13:46 UTC by Mocab

2021-12-28 22:11 UTC, KorbsStudio requested changes

2021-12-28 22:11 UTC, KorbsStudio commented on _posts/minecraft/plugins/2021-12-28-dynmap.md
> +![image](../../../assets/images/posts/plugins/dynmap/extra-port.png)
Using "../" isn't needed, you can just do:
```
/assets/images/posts/plugins/dynmap/extra-port.png".
```
or since we use Jekyll:
```
{{site.baseurl}}/assets/images/posts/plugins/dynmap/extra-port.png
```

2021-12-28 22:12 UTC, KorbsStudio commented
Other than that in format, everything looks good.
Howerver, I only check your format and metadata and don't review the entire article. 
Everything else is up to the support team.

2021-12-29 02:27 UTC, KorbsStudio approved these changes

2021-12-31 02:50 UTC, DaddyChimken commented on _posts/minecraft/plugins/2021-12-28-dynmap.md
> +To view the map, paste `http://IP:PORT` in your browser, replace `IP` with your server's IP and the `PORT` with your server's extra port, for example: `http://ult4.falix.gg:35773`.
```suggestion
To view the map, paste `http://IP:PORT` in your browser, replace `IP` with your server's IP and the `PORT` with your server's extra port. For example: `http://ult4.falix.gg:35773`.
```

2021-12-31 02:50 UTC, DaddyChimken commented on _posts/minecraft/plugins/2021-12-28-dynmap.md
> +The map may appear blank, players need to load chunks first in order for them to appear.
```suggestion
The map may appear blank, if so, players need to load the server's chunks in order for them to appear.
```

2021-12-31 05:21 UTC, KorbsStudio reviewed
New metadata

2021-12-31 22:57 UTC, DaddyChimken approved these changes

2021-12-31 22:57 UTC, merged