Edit: Getting started
FalixNodes-Software/help-center pull request #99
Opened 2022-01-29 03:11 UTC by Mocab

I have updated the Java version of this guide.

2022-01-29 21:26 UTC, KorbsStudio approved these changes

2022-01-30 03:22 UTC, DaddyChimken requested changes

2022-01-30 03:22 UTC, DaddyChimken commented on _posts/minecraft/general/2022-01-29-getting-started.md
> +4. You will be greeted with a message asking you to choose a server type. In this case Minecraft Java. Type in the number beside the option given, for example `1`.
```suggestion
4. You will be greeted with a message asking you to choose a server type. In this example, Minecraft Java. Type in the number beside the option you want. For example, enter `1` to select option 1.
```

2022-01-30 03:22 UTC, DaddyChimken commented on _posts/minecraft/general/2022-01-29-getting-started.md
> +5. You will be asked to choose a Server Software, if you don't know which to pick read our [Server Software guide](https://help.falixnodes.net/minecraft/general/server-softwares/).
```suggestion
5. You will be asked to choose a Server Software, if you don't know which to pick, read our [Server Software guide](https://help.falixnodes.net/minecraft/general/server-softwares/).
```

2022-01-30 03:22 UTC, DaddyChimken commented on _posts/minecraft/general/2022-01-29-getting-started.md
> +6. You will be prompted to choose a Minecraft version, for example `1.17.1`.
```suggestion
6. You will be prompted to choose a Minecraft version. For example, `1.17.1`.
```

2022-01-30 03:22 UTC, DaddyChimken commented on _posts/minecraft/general/2022-01-29-getting-started.md
> +2. Find and click on your server, make sure it's off.
```suggestion
2. Find and click on your server, make sure it's offline.
```

2022-01-30 03:22 UTC, DaddyChimken commented on _posts/minecraft/general/2022-01-29-getting-started.md
> +4. Under "JAVA VERSION", insert in a Java version:
```suggestion
4. Under "JAVA VERSION", insert a Java version:
```

2022-01-30 03:22 UTC, DaddyChimken commented on _posts/minecraft/general/2022-01-29-getting-started.md
> +    - if your server is **1.18** then type `1.17.0-custom=tgz+https://pterodactyl-api.catactyl.xyz/static-files/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz`.
Have you tested this works and is a 'permanent' solution?

2022-01-30 16:06 UTC, Mocab commented on _posts/minecraft/general/2022-01-29-getting-started.md
> +    - if your server is **1.18** then type `1.17.0-custom=tgz+https://pterodactyl-api.catactyl.xyz/static-files/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz`.
I got all the info there from exo, I will double check tomorrow morning.

2022-01-31 02:14 UTC, Mocab commented on _posts/minecraft/general/2022-01-29-getting-started.md
> +    - if your server is **1.18** then type `1.17.0-custom=tgz+https://pterodactyl-api.catactyl.xyz/static-files/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz`.
I have double checked everything, it works perfectly fine.

2022-01-31 04:22 UTC, DaddyChimken requested changes

2022-01-31 04:22 UTC, DaddyChimken commented on _posts/minecraft/general/2022-01-29-getting-started.md
> +> If this does not work, manually delete the `.jabba` folder in the File manager then start your server.
```suggestion
> If this does not work, manually delete the `.jabba` folder in the file manager, then start your server.
```

2022-01-31 04:23 UTC, DaddyChimken approved these changes

2022-01-31 04:23 UTC, merged